# Generated by Django 6.0.5 on 2026-05-24 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0002_alter_financingrequest_id'),
        ('merchants', '0002_alter_merchant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financingrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='financingrequest',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_requests', to='merchants.merchant'),
        ),
        migrations.AlterField(
            model_name='financingrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=10),
        ),
    ]
